divert(-1)define(`_RU', `ifelse(lang,`ru',§$1§)')
define(`_EN', `ifelse(lang,`en',§$1§)')
define(`_ES', `ifelse(lang,`es',§$1§)')
define(`_PL', `ifelse(lang,`pl',§$1§)')
define(`_PTBR', `ifelse(lang,`ptbr',§$1§)')
define(`_if',`_EN(`if')_RU(`если')_ES(`si')')
define(`_or',`_EN(`or')_RU(`или')_ES(`o')')
define(`_in',`_EN(`in')_RU(`в')_ES(`en')')
define(`_as',`_EN(`as')_RU(`как')_ES(`como')')
define(`_and',`_EN(`and')_RU(`и')_ES(`y')')
define(`_return',`_EN(`return')_RU(`возврат')_ES(`retornar')')
define(`_arg1',`_EN(`1st argument')_RU(`первый аргумент')_ES(`1er argumento')')
define(`_arg2',`_EN(`2nd argument')_RU(`второй аргумент')_ES(`2do argumento')')
define(`_arg3',`_EN(`3rd argument')_RU(`третий аргумент')_ES(`3er argumento')')
define(`_arg4',`_EN(`4th argument')_RU(`4-й аргумент')_ES(`4to argumento')')
define(`_numvecreg',`_EN(`number of vector registers passed')_RU(`количество переданных векторных регистров')_ES(`número de registros de vector pasados')')
define(`_print',`_EN(`print')_RU(`вывести')_ES(`imprimir')')
define(`_increment',`_EN(`increment')_RU(`инкремент')_ES(`incremento')')
define(`_input_value',`_EN(`input value')_RU(`входное значение')_ES(`valor de entrada')')
divert(0)
